### ISSUE TITLE
html error

### ISSUE THREAD

**Issue by bullsim** [FlyingDiver/BetterEmail#11]
I have an issue when i receive a particular email i can't parse it using reg parsing as its HTML and yet if i forward a plain text it works. Any ideas on how I parse it?

**Comment by FlyingDiver** [comment]
Write a smarter regex?  I'm not a regex expert, but it's supposed to be able to parse anything if you write the matching expression properly.  Examples of the string you're trying to parse and the regex expression you're working with would help.  But you would probably be better off asking the same question on stack exchange or some other forum with regex experts.

**Comment by bullsim** [comment]
Thanks, it’s throwing an error about the html message format though. Let me get you the error message

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bullsim** [comment]
Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: Polling IMAP Server
   Better Email Debug              Email: Doing checkMsgs
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: msg_ids = ['1']
   Better Email Debug              Email: Fetching Message # 1
   Better Email Debug              Email: IDLE Event Received
   Better Email                    Email: Received Message Subject: FW: Alert message from your system 22400298378 occurred
   Better Email                    Email: Received Message From: Simon Bullers <Simon@bullers.com>
   Better Email                    Email: Received Message To: home automation <caiborg@bullers.com>
   Better Email                    Email: Received Message Date: Tue, 4 Sep 2018 14:55:10 +0100
   Better Email Debug              Email: Received Message ID: 	<4fba9e077b994e3ba84db7a0467850e9@MM1P123MB1290.GBRP123.PROD.OUTLOOK.COM>
   Better Email Threaddebug        EmailcheckMsgs: Decoding multipart message
   Better Email Threaddebug        	found type: multipart/related
   Better Email Threaddebug        	found type: text/html
   Better Email Threaddebug        	found type: image/gif
   Better Email Error              Error decoding Body of Message # 1: No plain text segment found in multipart message
   Better Email Threaddebug        checkMsgs: Updating states on server: [{'value': 'Simon Bullers <Simon@bullers.com>', 'key': 'messageFrom'}, {'value': 'home automation <caiborg@bullers.com>', 'key': 'messageTo'}, {'value': 'FW: Alert message from your system 22400298378 occurred', 'key': 'messageSubject'}, {'value': 'Tue, 4 Sep 2018 14:55:10 +0100', 'key': 'messageDate'}, {'value': u'', 'key': 'messageText'}, {'value': '\t<4fba9e077b994e3ba84db7a0467850e9@MM1P123MB1290.GBRP123.PROD.OUTLOOK.COM>', 'key': 'lastMessage'}]
   Better Email Debug              triggerCheck: Checking Triggers for Device Email (1220365334)
   Better Email Debug              	Checking Trigger Alarm - Part set (367950281), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \bPart\b
   Better Email Debug              		No Match for Trigger Alarm - Part set (367950281)
   Better Email Debug              	Checking Trigger Alarm - Full set (734266336), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \bFull\b
   Better Email Debug              		No Match for Trigger Alarm - Full set (734266336)
   Better Email Debug              	Checking Trigger Alarm - Off (1321877643), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \wUnset\w
   Better Email Debug              		No Match for Trigger Alarm - Off (1321877643)
   Better Email Debug              Email: Deleting message # 1
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: checkMsgs complete

Here is what happens

**Comment by bullsim** [comment]
If i forward as a plain text it works
Trigger                         Monitor - Heating - Hallway - Stella
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: Polling IMAP Server
   Better Email Debug              Email: Doing checkMsgs
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: msg_ids = ['1']
   Better Email Debug              Email: Fetching Message # 1
   Better Email Debug              Email: IDLE Event Received
   Better Email                    Email: Received Message Subject: FW: Alert message from your system 22400298378 occurred
   Better Email                    Email: Received Message From: Simon Bullers <Simon@bullers.com>
   Better Email                    Email: Received Message To: home automation <caiborg@bullers.com>
   Better Email                    Email: Received Message Date: Tue, 4 Sep 2018 14:56:50 +0100
   Better Email Debug              Email: Received Message ID: <90936E7A-6FBA-45F7-8598-3F6D5DA7D5EE@bullers.com>
   Better Email Threaddebug        EmailcheckMsgs: Decoding multipart message
   Better Email Threaddebug        	found type: multipart/mixed
   Better Email Threaddebug        	found type: text/plain
   Better Email Threaddebug        checkMsgs: Updating states on server: [{'value': 'Simon Bullers <Simon@bullers.com>', 'key': 'messageFrom'}, {'value': 'home automation <caiborg@bullers.com>', 'key': 'messageTo'}, {'value': 'FW: Alert message from your system 22400298378 occurred', 'key': 'messageSubject'}, {'value': 'Tue, 4 Sep 2018 14:56:50 +0100', 'key': 'messageDate'}, {'value': u'\r\n\r\nFrom: Risco Cloud <iRisco@riscocloud.com>\r\nDate: Tuesday, 4 September 2018 at 14:54\r\nTo: "simon@bullers.com" <Simon@bullers.com>\r\nSubject: Alert message from your system 22400298378 occurred\r\n\r\n\r\n\r\n\r\nDear Simon Bullers\r\n\xa0\r\nEvent Part Set - \'House\', \'SIMON BULLERS\' occurred at your system at 04/09/2018 14:54:00\xa0\r\n\r\nKindest regards,\r\n<Risco Cloud>\r\n\xa0\r\n\r\n\r\n\xa0\r\n\r\n\xa0\xa0 \r\n\r\n', 'key': 'messageText'}, {'value': '<90936E7A-6FBA-45F7-8598-3F6D5DA7D5EE@bullers.com>', 'key': 'lastMessage'}]
   Better Email Debug              triggerCheck: Checking Triggers for Device Email (1220365334)
   Better Email Debug              	Checking Trigger Alarm - Part set (367950281), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \bPart\b
   Better Email Debug              		Executing Trigger Alarm - Part set (367950281), match: Part
   Trigger                         Alarm - Part set
   Better Email Debug              	Checking Trigger Alarm - Full set (734266336), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \bFull\b
   Better Email Debug              		No Match for Trigger Alarm - Full set (734266336)
   Better Email Debug              	Checking Trigger Alarm - Off (1321877643), regexMatch
   Better Email Debug              		Checking Device State messageText for Pattern: \wUnset\w
   Better Email Debug              		No Match for Trigger Alarm - Off (1321877643)
   Better Email Debug              Email: Deleting message # 1
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: IDLE Event Received
   Better Email Debug              Email: checkMsgs complete

**Comment by bullsim** [comment]
So i think this shows the regex works. But the issue appears to be higher up in the message part saying its got no plain text segment.

**Comment by FlyingDiver** [comment]
Yeah, I remember that.  As I recall, I assumed a multi-part message would have a plain text component.  Every client I tested with at the time did.  Whatever is sending that doesn't do that.  Is there some reason these need to be HTML, if they're intended for Indigo?

Otherwise I'll need to add that to the plugin, which I won't be able to get to until sometime in October.  If you really need that, please open another issue as an enhancement request.

**Comment by bullsim** [comment]
Ah yes I will open a ticket. Unfortunately my alarm system sends emails in this format I can send you the examples if it helps and so we want to parse it to trigger some actions.

Thanks

Simon


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FlyingDiver** [comment]
Post the examples in the enhancement issue.  Zip up the raw message text if at all possible.
