### ISSUE TITLE
runDialogForMenuAction() caught exception: 

### ISSUE THREAD

**Issue by smeee-again** [FlyingDiver/BetterEmail#15]
Currently the plugin hasn't been able to check mail for a few hours now.  I also cannot open the config for the plugin either; it just times out.  I even restarted the Indigo VM.

Jun 2, 2019 at 5:24:58 PM
   Error                           process (pid 536) failed to quit after polite request -- forcing it to quit now
   Stopped plugin "Better Email 7.2.4"
   Starting plugin "Better Email 7.2.4" (pid 655)
   Started plugin "Better Email 7.2.4"
   Error (client)                  timeout waiting for plugin response from com.flyingdiver.indigoplugin.betteremail for request UiGetValues1
   Error (client)                  timeout waiting for plugin response from com.flyingdiver.indigoplugin.betteremail for request CallPluginFunc
   Error (client)                  runDialogForMenuAction() caught exception: NSInvalidArgumentException -- *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
   Error (client)                  received unexpected packet response UiGetValues1 (waiting for CallPluginFunc)

**Comment by FlyingDiver** [comment]
Those errors usually indicate an open config dialog in the Indigo client that's failing to get some data from the plugin.  Disable the plugin, make sure there's no open device editing windows, then restart the plugin.

**Comment by smeee-again** [comment]
It definitely wasn't an open config dialog.  I even rebooted the Indigo VM and it still persisted.  Google did have issues as I found out later on and it started working again.  After the reboot, I didn't even open the Indigo client on the server, I opened the client on my local machine and it still had the same error.  I immediately went to the plugin and tried to change the logging level.

________________________________

**Comment by FlyingDiver** [comment]
So is it working now or not?

Is it possible that there was a client open on a different machine (or VM) when the error occurred?  I'm quite sure this is not an issue with the plugin itself, but is some sort of comm issue between the client and the server.

**Comment by smeee-again** [comment]
The only machine the Indigo client was open was on the machine I was on.

It is working now after Google fixed the issue within their cloud services:
https://www.theverge.com/2019/6/2/18649635/youtube-snapchat-down-outage

________________________________

**Comment by FlyingDiver** [comment]
Interesting.  So the client timed out because the communication between the plugin and Gmail failed?  Do you remember what the plugin was doing at the time?  Sending mail?  Receiving mail?  Were you attempting to use one of the menu commands (see _Error (client) runDialogForMenuAction()_ )

If we can figure out what was happening at the time, I can bring it up with Matt and Jay as a possible client bug.

**Comment by smeee-again** [comment]
That is what it appears to be, it couldn't communicate with Gmail and it would time out.  I have a dedicated email account for just the HA system that the Better Email Plugin uses.  No email client accesses it.  I did have to create a schedule to restart the plugin as I noticed at times, IMAP Idle would fail.  I noticed in the logs that the restart was having an issue and then it when I tried to change the debug level and ran into the issue.  I manually restarted the plugin a few times and nothing seemed to help, which is when I tried a restart of the Indigo VM.  Still nothing.  So I opened a browser and say unprocessed emails.  An hour or so after I opened the bug, it started working and some emails were processed and then later more.  So I think browser wise, Gmail was working, IMAP wise, it had issues.  Google had an issue in the past where IMAP would work, browser wouldn't.  So it sounds like Google probably had a frontend issue on the IMAP side; the browser and backend were working.

So, all the plugin should have been doing is trying to retrieve mail.  I use it for MyQ (since they can send an email alert and it is faster than the update on the MyQ plugin) and for Kevo locks.  If it is dark outside and the main garage door is opened, then it will turn on entry lights in the hallway.  There are a few other criteria which is based on if I was coming home rather than leaving.

I haven't down much with the Kevo alerts as of yet, but decided that I would use that email account for it.  I also use it for the RainMachine irrigation controller as well.

The only emails in the account were from MyQ though when this issue occurred.  It was the garage door opening and closing.  It was daylight hours so no action would have taken place.

Once Google fixed their issue, all emails were processed.

________________________________

**Comment by FlyingDiver** [comment]
Hmmm.  I'm thinking your plugin restart schedule collided with an operation with the Gmail server and that's what hung it.  The restart failed because the plugin was hung.  Maybe.  I'll have to think about that some.

On a related note, I haven't documented it anywhere, but I really do not recommend using Gmail with the plugin, because it has known IMAP issues.  Trying to get the Python IMAP libraries to act robustly enough to deal with those issues has been a challenge.

**Comment by smeee-again** [comment]
This is possible. This is the first time the issue has occurred though and I've used the plugin for over a year now. Wouldn't a reboot have cleared the issue though? It would've had no knowledge of what it was previously working on or got hung on. The only emails were unread in the inbox. I do have the plugin essentially archive the emails top keep the inbox clean.

I noticed that IMAP Idle had issues with Gmail between 1 and 2 hours, so I set the schedule for 30 minutes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FlyingDiver** [comment]
Unable to reproduce.
