### ISSUE TITLE
IMAP server connection error: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by tsh64** [FlyingDiver/BetterEmail#16]
Seeing this error each time better email map connects to imap.mail.me.com
Doing a quick web search there appears to be some underlying IMAP Python framework(s) that have the same issue and was patched.

**Comment by FlyingDiver** [comment]
Do you have a link for that search result?

Turn on detailed debug logging and do the connection again, then attach the log section to this issue.

**Comment by tsh64** [comment]
Thanks for looking into this.   

Here is the detailed log section:

Oct 13, 2019 at 08:21:51 AM
   Better Email Debug              logLevel = 5
   Reloading plugin "Better Email 7.2.4"
   Stopping plugin "Better Email 7.2.4" (pid 618)
   Better Email Debug              Removing Trigger Buena Vista checking in (769118315)
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Stopping device
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: shutting down
   Better Email Debug              smtp.mail.me.com <http://smtp.mail.me.com/>: Stopping device
   Better Email Debug              smtp.mail.me.com <http://smtp.mail.me.com/>: shutting down
   Better Email                    Shutting down Better Email
   Stopped plugin "Better Email 7.2.4"
   Starting plugin "Better Email 7.2.4" (pid 14305)
   Better Email Debug              logLevel = 5
   Started plugin "Better Email 7.2.4"
   Better Email                    Starting Better Email
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Device Version is up to date
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Starting device (imapAccount)
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Creating IMAP Server
   Better Email Threaddebug        smtp.mail.me.com <http://smtp.mail.me.com/>: Device Version is up to date
   Better Email Debug              smtp.mail.me.com <http://smtp.mail.me.com/>: Starting device (smtpAccount)
   Better Email Debug              Adding Trigger Buena Vista checking in (769118315)
   Better Email Debug              smtp.mail.me.com <http://smtp.mail.me.com/>: SMTP poll, 0 items in queue

Oct 13, 2019 at 08:23:04 AM
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Polling IMAP Server
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing connect using encryptionType = SSL
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing login()
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing select("INBOX")
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Mailbox list:
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: (\Noinferiors) "/" "INBOX"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Archive"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Deleted Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Drafts"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Junk"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Sent Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Processed-by-Indigo"
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing checkMsgs
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: msg_ids = [None]
   Better Email Error              IMAP server connection error: 'NoneType' object has no attribute 'split'


I did a web search on :'NoneType' object has no attribute 'split’ “ and can see a fix discussion on GitHub….hopefully its same related issue I am seeing, sample links below:

AttributeError: 'NoneType' object has no attribute 'split' · Issue #103 · OfflineIMAP/offlineimap <https://github.com/OfflineIMAP/offlineimap/issues/103>

KeyError 'labels' · Issue #101 · OfflineIMAP/offlineimap <https://github.com/OfflineIMAP/offlineimap/issues/101>

Regards, Tim

**Comment by FlyingDiver** [comment]
Different codebase, so it's not the same bug.  Related in cause, maybe.  This line says there's no messages to process:
```
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: msg_ids = [None]
```
But looks like it tried to anyway.

When you got this message, were there any emails in that INBOX to process?  Do you get the error if there is an email to process?

**Comment by tsh64** [comment]
That was fast!

Yes, it mostly empty, I just use the account (and another) for two Indigo systems to email each other everyday to prove they are still alive, otherwise they email me to investigate.

Thanks, let me know if you want me to test a proposed fix.

Regards, Tim

**Comment by tsh64** [comment]
Here is some more log info when an email is received…. 

The email content is as attached below…



Almost appears as if there is a “NoneType” email being presented on the first fetch as the email I sent clearly has a subject etc.   The move and delete work however so the email is processed but no trigger is fired..

Regards, Tim

Oct 13, 2019 at 09:17:41 AM
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Polling IMAP Server
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing connect using encryptionType = SSL
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing login()
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing select("INBOX")
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Mailbox list:
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: (\Noinferiors) "/" "INBOX"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Archive"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Deleted Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Drafts"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Junk"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Sent Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Processed-by-Indigo"
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing checkMsgs
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: msg_ids = ['1']
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Message # 1 Flags = '['1 (FLAGS (\\Deleted \\Seen))']'
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Fetching Message # 1
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Subject:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "From:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "To:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Date:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Threaddebug        checkMsgs: Decoding simple message
   Better Email Debug              triggerCheck: Checking Triggers for Device imap.mail.me.com <http://imap.mail.me.com/> (962889107)
   Better Email Debug              	Checking Trigger Buena Vista checking in (769118315), stringMatch
   Better Email Debug              		Checking Device State messageSubject for string: Buena Vista checking in
   Better Email Debug              		No Match for Trigger Buena Vista checking in (769118315)
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Copying message # 1 to Processed-by-Indigo
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Deleting message # 1
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: checkMsgs complete
   Better Email Debug              	Logged out from IMAP server: imap.mail.me.com <http://imap.mail.me.com/>

**Comment by FlyingDiver** [comment]
You can change the logging level to plain debug.  Don't need the detailed level for this now.

This line is troubling:
```
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Message # 1 Flags = '['1 (FLAGS (\\Deleted \\Seen))']'
```
It's fetching what looks like an already deleted, already seen email.  And then getting bogus data.

I guess I'll set up a test iCloud account and see what I get.

**Comment by tsh64** [comment]
I think its specific to just this account, its not happening on another and I can see it's getting the same result on each fetch when there are multiple emails to process. (Log below)

The accounts use app specific passwords, try accessing the account with this set up… (there are no personal emails in there and I can remove the access later)

Server: imap.mail.me.com
Enc:  SSL
Port: 993
Login: email13770skislope
Password: ejds-aytj-krxc-uape
Poll : 1 min

Regards, Tim


—————————
Example Log with 3 emails in inbox:

 Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Polling IMAP Server
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing connect using encryptionType = SSL
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing login()
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing select("INBOX")
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Mailbox list:
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: (\Noinferiors) "/" "INBOX"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Archive"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Deleted Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Drafts"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Junk"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Sent Messages"
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>:    Mailbox: () "/" "Processed-by-Indigo"
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Doing checkMsgs
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: msg_ids = ['1 2 3']
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Message # 1 Flags = '['1 (FLAGS (\\Seen))']'
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Fetching Message # 1
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Subject:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "From:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "To:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Date:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Threaddebug        checkMsgs: Decoding simple message
   Better Email Debug              triggerCheck: Checking Triggers for Device imap.mail.me.com <http://imap.mail.me.com/> (962889107)
   Better Email Debug              	Checking Trigger Buena Vista checking in (769118315), stringMatch
   Better Email Debug              		Checking Device State messageSubject for string: Buena Vista checking in
   Better Email Debug              		No Match for Trigger Buena Vista checking in (769118315)
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Copying message # 1 to Processed-by-Indigo
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Deleting message # 1
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Message # 2 Flags = '['2 (FLAGS (\\Seen))']'
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Fetching Message # 2
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Subject:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "From:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "To:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Error decoding "Date:" "None", error: coercing to Unicode: need string or buffer, NoneType found
   Better Email Threaddebug        checkMsgs: Decoding simple message
   Better Email Debug              triggerCheck: Checking Triggers for Device imap.mail.me.com <http://imap.mail.me.com/> (962889107)
   Better Email Debug              	Checking Trigger Buena Vista checking in (769118315), stringMatch
   Better Email Debug              		Checking Device State messageSubject for string: Buena Vista checking in
   Better Email Debug              		No Match for Trigger Buena Vista checking in (769118315)
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Copying message # 2 to Processed-by-Indigo
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Deleting message # 2
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: Message # 3 Flags = '['3 (FLAGS (\\Seen $IndigoProcessed $NotJunk NotJunk))']'
   Better Email Debug              imap.mail.me.comimap.mail.me.com: Message # 3 already seen, skipping...
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: checkMsgs complete
   Better Email Debug              	Logged out from IMAP server: imap.mail.me.com <http://imap.mail.me.com/>

**Comment by FlyingDiver** [comment]
Huh.  I do not get the error using one of my iCloud email accounts, but I do get it when using yours.
```
Oct 13, 2019 at 1:01:34 PM
   Better Email Debug              Test Account: Polling IMAP Server
   Better Email Debug              Test Account: Doing connect using encryptionType = SSL
   Better Email Debug              Test Account: Doing login()
   Better Email Debug              Test Account: Doing select()
   Better Email Debug              Test Account: Doing checkMsgs
   Better Email Debug              Test Account: msg_ids = 
   Better Email Error              Test Account: IMAP server connection error: 'NoneType' object has no attribute 'split'
```

**Comment by FlyingDiver** [comment]
And you say it works OK with other iCloud accounts you have?   What do you see in the webmail interface on iCloud.com?

**Comment by tsh64** [comment]
Yeah, it does appear to be specific to this account,   I can access the account via mail.app or iCloud Web mail and the inbox comes up on both…  but not with your plugin??   

I need to leave this AM, but will try to open your plugin later and see what’s being returned etc..  Tomorrow I can drop an email to the iCloud email team (I used to manage them a few years ago ;-).   And see if I can have them take a look at the account and see what’s up.   Ideally I will just create a small python script that demonstrates the error… if you have such a script that would be great…

Thanks again for looking into this so quickly.

Regards, Tim

**Comment by FlyingDiver** [comment]
On Oct 13, 2019, at 1:18 PM, tsh64 <notifications@github.com> wrote:
> 
> Yeah, it does appear to be specific to this account, I can access the account via mail.app or iCloud Web mail and the inbox comes up on both… but not with your plugin?? 
> 
> I need to leave this AM, but will try to open your plugin later and see what’s being returned etc.. Tomorrow I can drop an email to the iCloud email team (I used to manage them a few years ago ;-). And see if I can have them take a look at the account and see what’s up. Ideally I will just create a small python script that demonstrates the error… if you have such a script that would be great…

I might throw some more logging into that section and see if I get anything interesting.

I’m now trying to remember if I knew anyone working on the iCloud email team.  Did Seejo Pylappan work in that group?  If you were an Engineering manager, you probably know Todd Fernandez and Toni Trujillo Vian.  I was the manager of the AppleCare Enterprise Support team for years.  But I retired almost 12 years ago.  Small world.

j

**Comment by tsh64** [comment]
Ha - small world indeed,  I retired last year.  

After MobileMe failed to launch I was asked to take it over and ran MobileMe for a few years…  helped get it working before we switched to iCloud.   Last thing I did was ApplePay….  I was at Apple for 31 years so we probably ran into each other at some forum or other…

I think I remember Seejo, Todd and Toni for sure!

Now happily enjoying retirement and a bit of hacking with Indigo from time to time,,,  nice to meet you again Joe!

Regards, Tim

**Comment by FlyingDiver** [comment]
Fixed in https://github.com/FlyingDiver/Indigo-BetterEmail/releases/tag/7.2.7

First I had to fix a debug logging statement that was showing the wrong thing.  Then I had to add some additional tests to see if the message list was actually empty before I tried to process it.

**Comment by FlyingDiver** [comment]
In most cases the message list returned would be [''], an array with an empty string it it.  That seems to be the default case.  In your case, it was returning [None], and array with a None value in it.  Huh?  A normal (messages found) result is ['1 2 3 4'].  Go figure.

**Comment by tsh64** [comment]
Thank you!

BTW, nice plugin!

Regards, Tim

**Comment by tsh64** [comment]
Sorry me again…

I installed the new version and tried my email but there was no match on the string….  I added a few debug lines to your plugin.py (red below).   I send in an email with the subject “Buena Vista checking in” to email13770skislope but the pattern doesn’t match as the subject appears in the code to be blank.  Is this field still pointing to the “null” message or something?   Its still account specific and works the other way when I send an email to the other server.   

To give a little context on what I am doing.   I have two homes “Skislope” and “Buena Vista”.   At midnight they both enable a scheduled event to send me an email at 12:10AMl saying something is wrong, check the server.  Then at 12:02 they send each other an email that is caught by the other (trigger matches string) and that disables the 12:10 action.   So if all is well I don’t get the email and if one of the servers goes offline… I get an email.

I added these lines after line 137:

                       self.logger.debug("\t\tdevice.states[field] =" + device.states[field])
                       self.logger.debug("\t\tPattern =" + pattern)

Here is the log lines:

   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Received Message Subject: 
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Received Message From: 
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Received Message To: 
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Received Message Date: 
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Received Message ID: 
   Better Email Threaddebug        imap.mail.me.com <http://imap.mail.me.com/>: checkMsgs: Decoding simple message
   Better Email Debug              triggerCheck: Checking Triggers for Device imap.mail.me.com <http://imap.mail.me.com/> (962889107)
   Better Email Debug              	Checking Trigger Buena Vista checking in (769118315), stringMatch
   Better Email Debug              		Checking Device State messageSubject for string: Buena Vista checking in
   Better Email Debug              		No Match for Trigger Buena Vista checking in (769118315)
   Better Email Debug              		device.states[field] =
   Better Email Debug              		Pattern =Buena Vista checking in
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Copying message # 1 to Processed-by-Indigo
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Deleting message # 1
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: checkMsgs complete
   Better Email Debug              imap.mail.me.com <http://imap.mail.me.com/>: Logged out from IMAP server: 

Regards, Tim

**Comment by FlyingDiver** [comment]
OK, that's just plain weird.  I just sent a test message to that account.  It was received, but none of the states were filled in.  I'll work on it some more.

**Comment by tsh64** [comment]
Thanks… sorry to ruin your Sunday - no rush...

-TIm

**Comment by FlyingDiver** [comment]
Can you turn off your polling of that server for a while?  I need to use that account for testing since it's the only one that exhibits the behavior.

**Comment by FlyingDiver** [comment]
And just to confirm, you can use this account with Mail.app or the website and it receives and displays emails properly?  Because I'm getting no content back at all when I try to fetch a message.
```
   Better Email Debug              Test Account: Message # 6 content = '['6 ()']'
```
when it should look more like:
```
   Better Email Debug              flyingdiver@mac.com IMAP: Message # 1 content = '[('1 (RFC822 {3917}', 'Received: from st11p00im-smtpin014.me.com ([17.172.80.63])\r\n
```

**Comment by FlyingDiver** [comment]
The more I look at it, the more I'm sure that the specific IMAP server that's hosting your account is broken.  It just won't return any content to me at all.

**Comment by tsh64** [comment]
Thanks Joe,   Sorry I am cycling and didn’t see your note.    I will recheck webmail again to be sure but earlier I was seeing other emails on that account.   Maybe the account is on their “new” IMAP server.   We (they) used to use Oracle‘s but I know there was an effort to write their own.   If you can share any additional log info I can contact the eng manager who I believe is a guy called John St George now.  
Will be back in a few hours and will  check mail then too. 

Regards, Tim

**Comment by tsh64** [comment]
Yes, and never had any issues in all the time I used The built in email in indigo.  The account is years old.  

Regards, Tim

**Comment by FlyingDiver** [comment]
> Yes, and never had any issues in all the time I used The built in email in indigo.  The account is years old.

They changed something.  :(

**Comment by FlyingDiver** [comment]
The critical info is https://github.com/FlyingDiver/Indigo-BetterEmail/issues/16#issuecomment-541460053

Same code, two different iCloud.com accounts, different results.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-BetterEmail/releases/tag/7.2.8

**Comment by tsh64** [comment]
That did it, thanks so much!

Regards, Tim

**Comment by FlyingDiver** [comment]
So the short answer, if you decide to talk to the folks at the mother ship, is that your server won't return any content for an IMAP request for the 'RFC822' key.  It does return data for a 'BODY[]' key.  BODY is the newer IMAP standard, RFC822 is an older one.  But dropping backwards compatibility is not a good thing.

**Comment by tsh64** [comment]
Thanks, I will drop John a note as this is quite specific and perhaps not an intentional drop of the older standard.

Regards, Tim

**Comment by FlyingDiver** [comment]
Current code implements both keys, so this is fixed in the next release.
