### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaveL17** [FlyingDiver/BetterEmail#18]
Would it be possible to add a css file to the payload for HTML formatted messages?  Here's the main usage case I have in mind:

Each day, I send an email with the plugin that contains any errors that were written to the Indigo log during the prior day. I would like to format of the text so that it doesn't wrap when rendered in Mail.app.

I'm not sure how hard this would be to implement.  Thanks for considering.

EDIT: I have discovered that the plugin will pass in-line css, so this has become less urgent for me (not that it was *that* urgent before....

```
message_text = """
This is some text.

<h1 style="color:blue;">A Blue Heading</h1>

<p style="white-space:nowrap;"> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>
"""
```

**Comment by FlyingDiver** [comment]
I don't think it's possible to add a CSS file.  I'm just handing the entire text string (after substitutions) to the MIMEText class object of https://docs.python.org/2.7/library/email.mime.html to get a MIME message that I send.

**Comment by FlyingDiver** [comment]
Yeah, I was going to suggest you try that.
