### ISSUE TITLE
Repeated Errors

### ISSUE THREAD

**Issue by rycardo** [FlyingDiver/BetterEmail#3]
Hey,

I keep getting these errors, it says no mailbox selected, I'm not sure where it determines that, both my IMAP and SMTP devices are fully configured (correctly).

I get many of these, I even tried restarted the plugin every 4 hours, and that doesn't resolve it. 

2018-04-27 14:59:48.169	Better Email Warning	Email Indigo IMAP: IDLE Event Timeout, reconnecting
2018-04-27 14:59:48.170	Better Email Error	Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 246, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/BetterEmail.indigoPlugin/Contents/Server Plugin/IMAPServer.py", line 259, in pollCheck
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/BetterEmail.indigoPlugin/Contents/Server Plugin/imaplib2.py", line 739, in close
error: No mailbox selected.

2018-04-27 14:59:48.171	Better Email Error	plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by rycardo** [comment]
I forgot to mention, I'm using the latest version with the latest Indigo version.

**Comment by FlyingDiver** [comment]
What IMAP provider are you using?

**Comment by rycardo** [comment]
WOW Fast response!   I'm not even finished :) 
I use NamesPro.ca (Canada).   I also get this error many times on many messages:
2018-04-27 15:00:05.458	Better Email Error	Email Indigo IMAP: Error fetching FLAGS for Message # 7: argument of type 'NoneType' is not iterable
I'm not sure if they are related or not. 

Thanks for your help.

**Comment by rycardo** [comment]
I use one of NamesPro's unix servers, it's standard IMAP (or POP but no) and SMTP.

**Comment by FlyingDiver** [comment]
I don't think the errors are related.  

Can you turn on debug level logging, then restart the plugin.  After you see the error reappear, disable the plugin, then zip up the plugin log file and attach it to this issue.  I need  "Indigo 7/Logs/com.flyingdiver.indigoplugin.betteremail/plugin.log"

**Comment by rycardo** [comment]
yeah, no problem.

**Comment by rycardo** [comment]
I had debug (or higher) level on before, but I didn't see anything that stood out, so put it on warning.  As soon as I notice it come up, I'll attach it.

**Comment by FlyingDiver** [comment]
Other direction.  Warning puts LESS in the logs.  Maybe use "Detailed Debugging" if that's an option for that plugin.  I have that enabled on some of them, don't recall for BE off the top of my head.

**Comment by rycardo** [comment]
Yeah, I said it correctly, but probably wasn't clear what I was trying to say. I had logging turned up to debug (or more logging) after I first noticed this issue. I looked at the logging, but nothing stood out to me, so lowered the logging until I had time to get back to this. Which is today.  I'v put it back to debug. I'm looking at the event logs to see if anything specific triggers it.  So far no.  but it will come up

**Comment by FlyingDiver** [comment]
The root cause is my timeout on the IMAP IDLE, which is this message:

`2018-04-27 14:59:48.169	Better Email Warning	Email Indigo IMAP: IDLE Event Timeout, reconnecting
`
The plugin assumes that the IMAP server has dropped the connection if it goes an hour without an IDLE event.  The debug log will tell me if it's getting the events at all.

**Comment by FlyingDiver** [comment]
Would you move that FLAGS error message to another issue please.

**Comment by FlyingDiver** [comment]
Please try 7.2.1-b1 at https://github.com/FlyingDiver/Indigo-BetterEmail/releases/tag/7.2.1-b1

**Comment by rycardo** [comment]
The issue appears to be resolved. Thank you!!!
