### ISSUE TITLE
Fetching Message Error

### ISSUE THREAD

**Issue by rycardo** [FlyingDiver/BetterEmail#4]
It appears this error is preventing these messages from being processed, so every time mail comes in, there are a handful of these message numbers that have this error.  This is what is in my Event Log after setting level to Debug.  If there is more in your log file, I can attach it if you would like.

```
 Better Email Debug              Email Indigo IMAP: Checking Message # 7
   Better Email Debug              Email Indigo IMAP: Fetching Message # 7
   Better Email Error              Error fetching Message # 6: 'NoneType' object has no attribute '__getitem__'
   Better Email Error              exception in deviceStartComm(Email Indigo IMAP): local variable 'message' referenced before assignment

```

**Comment by FlyingDiver** [comment]
Are you sure you're using the latest plugin version?  The current version does not have the text string "Checking Message #" in it anywhere.

**Comment by FlyingDiver** [comment]
And I can't figure out how the message numbers went from 7 to 6.  Hmm.

**Comment by rycardo** [comment]
I checked for an update before going online to report the situation, but let me double check.

**Comment by rycardo** [comment]
When I highlight Better Email in the Plugins menu, it says: "About Better Email v7.2.0". I checked both on my client machine (MBP) and the actual Indigo machine (mini).

**Comment by rycardo** [comment]
Am I behind by 18 releases, or I did I mis-say 7.20 earlier?

**Comment by rycardo** [comment]
I think the coded text above is in reverse order because I pasted it from the 2018-04-27 Events.txt file not from the Indigo Events window.  I just saw a bunch of Better Email log lines go through the Events window, and it has messages in sequential order ...6,7,8... etc.

**Comment by FlyingDiver** [comment]
7.2.0 is current, but grab the latest it from http://www.indigodomo.com/pluginstore/30/ just to be sure.

**Comment by rycardo** [comment]
I reinstalled from the link, based on file timestamps and the version number it's the same as I had installed  prior - and I had misspoken when I said 7.20 - it was a good double check. Neither error has happened yet. 
I have a question though. In turning on this additional logging, its going through each of the emails each time (and skipping previous ones), I don't want to delete messages, although is it possible for the plugin to move them to a different folder. For example a "processed" folder. I actually have a folder with that name, but I don't see how to have the plugin to move them. A bit off topic from this bug, if you want me to post on the forums, I'm happy to.  One way to do it would be to create a mail rule and applescript (in Mail), which doesn't act on the current incoming message, but on any message in the Inbox that is Read and > 1 day old.

**Comment by FlyingDiver** [comment]
If you want to create an enhancement request, that's fine.

**Comment by rycardo** [comment]
I'll create the request, yeah. Attached is a copy of the log file for the fetch error. I disabled the plugin as soon as I noticed the error, so it should be near the most recent entries.  We use Apple's Find Friends to do Geo-Fencing for Home/Away. This particular email is one of those.
[better-email-log-rycardo-plugin.log.zip](https://github.com/FlyingDiver/Indigo-BetterEmail/files/1958269/better-email-log-rycardo-plugin.log.zip)

**Comment by FlyingDiver** [comment]
Do you edit that INBOX from other email clients?  I think we might be running into a race condition where the INBOX is changing while the plugin is iterating through all the hundreds of messages.

**Comment by FlyingDiver** [comment]
Please try 7.2.1-b1 at https://github.com/FlyingDiver/Indigo-BetterEmail/releases/tag/7.2.1-b1

**Comment by rycardo** [comment]
The issue appears to be resolved, thank you!
