### ISSUE TITLE
Two IMAP Devices Using Same Configuration

### ISSUE THREAD

**Issue by rycardo** [FlyingDiver/BetterEmail#6]
I just discovered this after working with the enhancement. I have two IMAP devices, one for iCloud and one for NamesPro. NamesPro move to folder is "INBOX.Processed" (thank you again) and iCloud is only "Processed". 

When incoming mail is being processed for both IMAP devices, the plugin is using "INBOX.Processed" for both. So the iCloud device is getting that error saying the mailbox doesn't exist, which of course it doesn't since it's looking for "INBOX.Processed" instead of "Processed".

**Comment by FlyingDiver** [comment]
Hmm.  That string is supposed to be per-device.  I'll take a look at it again.

**Comment by FlyingDiver** [comment]
Cannot replicate.  I have two IMAP servers in my setup.  I set one to move messages to "Trash", the other to move them to "Processed".  Sent an email to each, and both handled them as expected.

Please double check your device settings.

**Comment by rycardo** [comment]
Hey, I just double checked the settings, added in additional log messages, and created two test messages, one to each account, the messages **are** going to the **correct** account/folder. They are not mixing as I reported.  What is interesting is those messages I initial saw (and prompted me to create the bug report) are still in the wrong account's Processed folder. I'm even more puzzled by that now, but it is safe to say not from the plugin-in. My apologies for the mistaken issue report.

**Comment by rycardo** [comment]
Although wouldn't it be nice if all "issues" were solved like this?   Have a great day, and thanks again!!
