### ISSUE TITLE
Failure Error

### ISSUE THREAD

**Issue by farberm** [FlyingDiver/BetterEmail#9]
For both my accounts, State column  reads failure for incoming (gmail and icloud) after updating to latest driver. The smtp (outgoing) says success. I also turned on IDLE. I turned on the debug msg and have the following:

Not sure what is going on. Sorry for the problems.

   Started plugin "Better Email 7.2.3"
   Better Email                    Starting Better Email
   Better Email Threaddebug        Better Email Gmail incoming: Device Version is up to date
   Better Email Debug              Better Email Gmail incoming: Starting device (imapAccount)
   Better Email Debug              Better Email Gmail incoming: Creating IMAP Server
   Better Email Debug              Better Email Gmail incoming: Using IMAP IDLE
   Better Email Debug              Better Email Gmail incoming: Doing connect using encryptionType = SSL
   Better Email Debug              Better Email Gmail incoming: Doing login()
   Better Email Debug              Better Email Gmail incoming: Doing select("INBOX")
   Better Email Threaddebug        Better Email Gmail incoming: Mailbox list:
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "INBOX"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "Notes"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "Personal"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "Receipts"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "Travel"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "Work"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasChildren) "/" "[Airmail]"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Done"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Memo"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Snooze"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/To Do"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasChildren \Noselect) "/" "[Gmail]"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\All \HasNoChildren) "/" "[Gmail]/All Mail"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren \Important) "/" "[Gmail]/Important"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasChildren) "/" "[Mailbox]"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Mailbox]/Later"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Mailbox]/To Buy"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Mailbox]/To Read"
   Better Email Threaddebug        Better Email Gmail incoming:    Mailbox: (\HasNoChildren) "/" "[Mailbox]/To Watch"
   Better Email Debug              Better Email Gmail incoming: idleIMAPThread() called
   Better Email Threaddebug        Better Email Gmail Outgoing: Device Version is up to date
   Better Email Debug              Better Email Gmail Outgoing: Starting device (smtpAccount)
   Better Email Threaddebug        Better Email Icloud Incoming: Device Version is up to date
   Better Email Debug              Better Email Icloud Incoming: Starting device (imapAccount)
   Better Email Debug              Better Email Icloud Incoming: Creating IMAP Server
   Better Email Debug              Better Email Icloud Incoming: Using IMAP IDLE
   Better Email Debug              Better Email Icloud Incoming: Doing connect using encryptionType = SSL
   Better Email Debug              Better Email Icloud Incoming: Doing login()
   Better Email Debug              Better Email Icloud Incoming: Doing select("INBOX")
   Better Email Threaddebug        Better Email Icloud Incoming: Mailbox list:
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\NoInferiors) "/" INBOX
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "Apple Mail To Do"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Archive
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "Deleted Messages"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Drafts
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Junk
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "Junk (.Mac)"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "New Folder"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Notes
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "Sent Messages"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Starred
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" Trash
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasChildren) "/" "[Airmail]"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Done"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Memo"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/Snooze"
   Better Email Threaddebug        Better Email Icloud Incoming:    Mailbox: (\HasNoChildren) "/" "[Airmail]/To Do"
   Better Email Debug              Better Email Icloud Incoming: idleIMAPThread() called
   Better Email Threaddebug        Better Email Icloud Outgoing: Device Version is up to date
   Better Email Debug              Better Email Icloud Outgoing: Starting device (smtpAccount)
   Better Email Debug              Better Email Gmail Outgoing: SMTP poll, 0 items in queue
   Better Email Debug              Better Email Icloud Outgoing: SMTP poll, 0 items in queue

**Comment by FlyingDiver** [comment]
I don’t see any actual errors in that log. Turn logging down to plain debugging and send an email to that account.

**Comment by FlyingDiver** [comment]
Are you still getting errors?

**Comment by FlyingDiver** [comment]
No response, cannot duplicate.
